services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: demopwd
    ports:
      - "3301:5432"
    volumes:
      - ./db/postgres/init:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data
